import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

const pkgRaw = await readFile(resolve(repoRoot, 'package.json'), 'utf8');
const pkg = JSON.parse(pkgRaw);
const version = pkg.version;

if (typeof version !== 'string' || version.length === 0) {
  throw new Error(`Unable to read version from package.json: ${version}`);
}

const banner =
  '// AUTO-GENERATED by scripts/write-version.mjs. Do not edit by hand;\n' +
  '// keep package.json as the single source of truth for the wrapper version.\n';

const tsTarget = resolve(repoRoot, 'src/version.ts');
const tsBody = `${banner}\nexport const PINWHEEL_CAPACITOR_WRAPPER_VERSION = '${version}';\n`;
await writeFile(tsTarget, tsBody, 'utf8');

const swiftTarget = resolve(repoRoot, 'ios/Sources/PinwheelPlugin/Version.swift');
const swiftBody =
  banner.replace(/^/gm, '') +
  '\nimport Foundation\n\n' +
  `enum PinwheelCapacitorWrapper {\n    static let version: String = "${version}"\n}\n`;
await writeFile(swiftTarget, swiftBody, 'utf8');

console.log(`wrote wrapper version ${version} to src/version.ts and ios Version.swift`);
