import type { PluginListenerHandle } from '@capacitor/core';

export interface PinwheelOpenOptions {
  /**
   * Link token generated by Pinwheel.
   */
  linkToken: string;

  /**
   * Version string for THIS Capacitor wrapper (i.e. `@pinwheel/capacitor-sdk`),
   * forwarded to Pinwheel Link as `sdk_version`. This is **not** the underlying
   * native SDK version (PinwheelSDK on iOS, pinwheel-android on Android) — those
   * are pinned in the podspec / Gradle build and are independent of this value.
   *
   * If omitted, the wrapper's `package.json` version is used automatically; you
   * generally do not need to set this.
   */
  sdkVersion?: string;

  /**
   * Enable dark mode styling in the native SDK.
   *
   * Default: false
   */
  useDarkMode?: boolean;

  /**
   * Load Link using the CSP-enabled secure origin.
   *
   * Default: false
   */
  useSecureOrigin?: boolean;

  mode?: 'development' | 'sandbox' | 'production';
  environment?: 'local' | 'staging' | 'production';

  /**
   * Optional Link UI URL override (local development / staging).
   */
  linkURL?: string;
}

export type PinwheelEventName =
  | 'open'
  | 'select_employer'
  | 'select_platform'
  | 'incorrect_platform_given'
  | 'login'
  | 'login_attempt'
  | 'input_allocation'
  | 'input_required'
  | 'screen_transition'
  | 'card_switch_begin'
  | 'dd_form_begin'
  | 'dd_form_create'
  | 'dd_form_download'
  | 'exit'
  | 'success'
  | 'error'
  | 'other_event'
  | 'external_account_connected'
  | 'bill_switch_success'
  | 'bill_switch_failure'
  | 'bill_removed'
  | 'bill_added'
  | 'bill_edited'
  | 'bill_marked_inactive'
  | 'bill_switch_platforms_added'
  | 'bill_switch_platforms_removed'
  | 'bill_cancel_success'
  | 'bill_cancel_failure'
  | 'calendar_sync'
  | 'customer_terms_accepted'
  | 'user_activated'
  | 'merchant_login_success';

export interface PinwheelTarget {
  accountType: string;
  accountName?: string;
}

export interface PinwheelAllocation {
  type: string;
  value?: number;
  target?: PinwheelTarget;
}

export interface PinwheelParams {
  action?: string;
  allocation?: PinwheelAllocation;
}

export interface PinwheelSuccessPayload {
  accountId: string;
  platformId: string;
  job: string;
  params?: PinwheelParams;
}

export interface PinwheelError {
  type: string;
  code: string;
  message: string;
  pendingRetry?: boolean;
}

export interface PinwheelSelectedEmployerPayload {
  selectedEmployerId: string;
  selectedEmployerName: string;
}

export interface PinwheelSelectedPlatformPayload {
  selectedPlatformId: string;
  selectedPlatformName: string;
}

export interface PinwheelLoginPayload {
  accountId: string;
  platformId: string;
}

export interface PinwheelLoginAttemptPayload {
  platformId: string;
}

export interface PinwheelInputAllocationPayload {
  action?: string;
  allocation?: PinwheelAllocation;
}

export interface PinwheelDDFormCreatePayload {
  url: string;
}

export interface PinwheelScreenTransitionPayload {
  screenName: string;
  selectedEmployerId?: string;
  selectedEmployerName?: string;
  selectedPlatformId?: string;
  selectedPlatformName?: string;
}

export type PinwheelOtherEventPayloadValueType = 'string' | 'number' | 'boolean';

export interface PinwheelOtherEventPayloadItem {
  key: string;
  value: string;
  type: PinwheelOtherEventPayloadValueType;
}

export interface PinwheelOtherEventPayload {
  name: string;
  payload: PinwheelOtherEventPayloadItem[];
}

export interface PinwheelBillSwitchPayload {
  platformId: string;
  platformName: string;
  isIntegratedSwitch: boolean;
  frequency: string;
  nextPaymentDate: string;
  amountCents: number;
  accountId?: string;
}

export interface PinwheelBillPayload {
  platformId: string;
  platformName: string;
  frequency: string;
  nextPaymentDate: string;
  amountCents: number;
}

export interface PinwheelBillSwitchPlatform {
  id: string;
  name: string;
}

export interface PinwheelBillSwitchPlatformsPayload {
  platforms: PinwheelBillSwitchPlatform[];
}

export interface PinwheelCalendarSyncPayload {
  calendarType: 'google' | 'outlook';
}

export interface PinwheelUserActivatedPayload {
  solutionName: string;
}

export interface PinwheelExternalAccountConnectedPayload {
  institutionName: string;
  accountName: string;
}

export type PinwheelEventPayloadByName = {
  open: undefined;
  select_employer: PinwheelSelectedEmployerPayload;
  select_platform: PinwheelSelectedPlatformPayload;
  incorrect_platform_given: unknown;
  login: PinwheelLoginPayload;
  login_attempt: PinwheelLoginAttemptPayload;
  input_allocation: PinwheelInputAllocationPayload;
  input_required: undefined;
  screen_transition: PinwheelScreenTransitionPayload;
  card_switch_begin: undefined;
  dd_form_begin: undefined;
  dd_form_create: PinwheelDDFormCreatePayload;
  dd_form_download: undefined;
  exit: PinwheelError | undefined;
  success: PinwheelSuccessPayload;
  error: PinwheelError;
  other_event: PinwheelOtherEventPayload;
  external_account_connected: PinwheelExternalAccountConnectedPayload;
  bill_switch_success: PinwheelBillSwitchPayload;
  bill_switch_failure: PinwheelBillSwitchPayload;
  bill_removed: PinwheelBillPayload;
  bill_added: PinwheelBillPayload;
  bill_edited: PinwheelBillPayload;
  bill_marked_inactive: PinwheelBillPayload;
  bill_switch_platforms_added: PinwheelBillSwitchPlatformsPayload;
  bill_switch_platforms_removed: PinwheelBillSwitchPlatformsPayload;
  bill_cancel_success: PinwheelBillSwitchPayload;
  bill_cancel_failure: PinwheelBillSwitchPayload;
  calendar_sync: PinwheelCalendarSyncPayload;
  customer_terms_accepted: undefined;
  user_activated: PinwheelUserActivatedPayload;
  merchant_login_success: PinwheelLoginPayload;
};

export interface PinwheelEvent<Name extends PinwheelEventName = PinwheelEventName> {
  name: Name;
  payload?: PinwheelEventPayloadByName[Name];
}

export interface PinwheelPlugin {
  /**
   * Open Pinwheel Link in a native modal.
   */
  open(options: PinwheelOpenOptions): Promise<void>;

  /**
   * Close the currently presented Pinwheel modal (if any).
   */
  close(): Promise<void>;

  /**
   * Canonical event stream that includes the event name and payload.
   */
  addListener(eventName: 'event', listenerFunc: (event: PinwheelEvent) => void): Promise<PluginListenerHandle>;

  /**
   * Convenience listeners (payload-only) to mirror existing Flutter/RN patterns.
   */
  addListener(
    eventName: 'success',
    listenerFunc: (payload: PinwheelSuccessPayload) => void,
  ): Promise<PluginListenerHandle>;
  addListener(eventName: 'exit', listenerFunc: (payload?: PinwheelError) => void): Promise<PluginListenerHandle>;
  addListener(eventName: 'error', listenerFunc: (payload: PinwheelError) => void): Promise<PluginListenerHandle>;
  addListener(eventName: 'login', listenerFunc: (payload: PinwheelLoginPayload) => void): Promise<PluginListenerHandle>;
  addListener(
    eventName: 'loginAttempt',
    listenerFunc: (payload: PinwheelLoginAttemptPayload) => void,
  ): Promise<PluginListenerHandle>;

  removeAllListeners(): Promise<void>;
}
